tasks:
  - init: pip3 install -r ./requirements.txt && echo "export PORT=8080" >> ~/.bashrc && echo "export AIRFLOW_HOME=~" >> ~/.bashrc 
  - command: export AIRFLOW_HOME=~  && export PORT=8080 && sleep 4 && airflow webserver -p $PORT 
  - command: sleep 5 && airflow initdb && airflow scheduler