tasks:
  - init: pip3 install -r ./requirements.txt && airflow initdb && echo "export PORT=8080" >> ~/.bashrc
  - command: export PORT=8080 && sleep 4 && airflow webserver -p $PORT -D & sleep 20 && airflow scheduler